force-app/main/default/objects/AtividadeInterno__c/AtividadeInterno__c.object-meta.xml
<CustomObject>
    <label>AtividadeInterno</label>
    <nameField>
        <label>Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AtividadeInterno</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AtividadeInterno__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descricao</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AtividadeInterno__c/fields/Hora__c.field-meta.xml
<CustomField>
    <fullName>Hora__c</fullName>
    <label>Hora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AtividadeInterno__c/fields/HoraExtra__c.field-meta.xml
<CustomField>
    <fullName>HoraExtra__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HoraExtra</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CallIntegrationDiaADiaHandler.cls
public with sharing class CallIntegrationDiaADiaHandler {
    public static void afterInsert(List<AtividadeInterno__c> atividadeList) {
        String name;
        String userName;
        String descricao;
        String nomeProjeto;
        String hora;
        String dataAtividade;
        Boolean horaExtra;
        for (AtividadeInterno__c ativ : atividadeList) {
            name = ativ.Name;
            userName = ativ.Username__c;
            descricao = ativ.Descricao__c;
            nomeProjeto = ativ.Projeto__c;
            hora = ativ.Hora__c;
            dataAtividade = ativ.Data__c;
            horaExtra = ativ.HoraExtra__c;
        }
    }
}