force-app/main/default/objects/Atividade__c/Atividade__c.object-meta.xml
<CustomObject>
    <label>Atividade</label>
    <nameField>
        <label>Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atividades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Atividade__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descricao</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Hora__c.field-meta.xml
<CustomField>
    <fullName>Hora__c</fullName>
    <label>Hora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <label>Projeto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SerealizeJsonDiaADia.cls
public with sharing class SerealizeJsonDiaADia {
    public with sharing class MeuJson {
        
        public List<TAtividades> atividades;
        
    }
    
    public with sharing class TAtividades {
        public String name;
        public String dataAtividade;
        public String hora;
        public String nomeProjeto;
        public String descricao;
        public String userName;
        public Boolean horaExtra;
    }
    
    public static String IntegrationContractJson(List<Atividade__c> ativList) {
       
        List<TAtividades> atividadesList = new List<TAtividades>();
        
        for(Atividade__c ativ : ativList) {
        TAtividades atividade = new TAtividades ();
            atividade.name=ativ.Name;
            atividade.dataAtividade=ativ.Data__c;
            atividade.hora=ativ.Hora__c;
            atividade.nomeProjeto=ativ.Projeto__c;
            atividade.descricao=ativ.Descricao__c;
            atividade.userName=ativ.Username__c;
            atividade.horaExtra=ativ.HoraExtra__c;
            atividadesList.add(atividade);
            System.debug(atividade);
        }       

        MeuJson json = new MeuJson();
        json.atividades=atividadesList;
        
       
       
        String jsonSerealized = System.JSON.serialize(json);
        System.debug(jsonSerealized);
        return jsonSerealized;
    }
}