force-app/main/default/objects/Atividade__c/Atividade__c.object-meta.xml
<CustomObject>
    <label>Atividade</label>
    <nameField>
        <label>Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atividades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Atividade__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descricao</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Hora__c.field-meta.xml
<CustomField>
    <fullName>Hora__c</fullName>
    <label>Hora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <label>Projeto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BuscaDiaaDiaTest.cls
@isTest
public with sharing class BuscaDiaaDiaTest {
    @isTest public static void BuscaDiaaDiaTest() {
        RestRequest req = new RestRequest();
        req.requestUri = 'https://jlns-dev-ed.my.salesforce.com/services/apexrest/BuscaDiaADia';
        req.httpMethod = 'POST';
        req.requestBody=Blob.valueOf('{"userName": "joao@test.com"}');

        RestContext.request = req;
        Atividade__c ativ = new Atividade__c(
            Name='Joao', Data__c='2021-04-05', Projeto__c='teste', Hora__c='teste', Descricao__c='teste', HoraExtra__c =true, Username__c='joao@test.com'
        );
        insert ativ;

        BuscaDiaADia.receiveData();
    }
}