force-app/main/default/objects/Atividade__c/Atividade__c.object-meta.xml
<CustomObject>
    <label>Atividade</label>
    <nameField>
        <label>Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atividades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Atividade__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descricao</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Hora__c.field-meta.xml
<CustomField>
    <fullName>Hora__c</fullName>
    <label>Hora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Jsonrecebido__c.field-meta.xml
<CustomField>
    <fullName>Jsonrecebido__c</fullName>
    <label>Jsonrecebido</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <label>Projeto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegracaoDiaADia.cls
@RestResource(urlMapping='/IntegracaoDiaADia')
global with sharing class IntegracaoDiaADia {
 
    @HttpPost
    global static String receiveData() {        
        Boolean Okrequest = false;
        RestRequest req = RestContext.request;               
        String json=req.requestBody.toString();
        DeserealizeJsonDiaaDia activity = (DeserealizeJsonDiaaDia)System.JSON.deserialize(json, DeserealizeJsonDiaaDia.class);
        String returnMessage;
        if (activity.atividade.name==null || activity.atividade.name=='') {
            RestContext.response.statusCode = 400 ; 
            returnMessage = 'Erro, Enviar o campo nome corretamente';  
            Okrequest = true;   
        }
        if (activity.atividade.dataAtividade==null || activity.atividade.dataAtividade=='') {
            RestContext.response.statusCode = 400 ;
            returnMessage = 'Erro, Enviar o campo data corretamente';  
            Okrequest = true;  
        }
        if (activity.atividade.descricao==null || activity.atividade.descricao=='') {
            RestContext.response.statusCode = 400 ;
            returnMessage = 'Erro, Enviar o campo descrição corretamente';   
            Okrequest = true; 
        }
        if (activity.atividade.hora==null || activity.atividade.hora=='') {
            RestContext.response.statusCode = 400 ;
            returnMessage = 'Erro, Enviar o campo tempo corretamente';   
            Okrequest = true; 
        }
        if (activity.atividade.horaExtra==null) {
            RestContext.response.statusCode = 400 ;
            returnMessage = 'Erro, Enviar o campo hora extra corretamente'; 
            Okrequest = true;   
        }
        if (activity.atividade.nomeProjeto==null || activity.atividade.nomeProjeto=='') {
            RestContext.response.statusCode = 400 ;
            returnMessage = 'Erro, Enviar o campo projeto corretamente';    
            Okrequest = true;
        }
        if (activity.atividade.userName==null || activity.atividade.userName=='') {
            RestContext.response.statusCode = 400 ;
            returnMessage = 'Erro, Enviar o campo username corretamente';  
            Okrequest = true;  
        }
        
        if (Okrequest ==false) {
        Atividade__c ativ = new Atividade__c();
        ativ.Name=activity.atividade.name;
        ativ.Jsonrecebido__c=json;
        ativ.Data__c=activity.atividade.dataAtividade;
        ativ.Descricao__c=activity.atividade.descricao;
        ativ.Hora__c=activity.atividade.hora;
        ativ.HoraExtra__c=activity.atividade.horaExtra;
        ativ.Projeto__c=activity.atividade.nomeProjeto;
        ativ.Username__c=activity.atividade.userName;
        insert ativ;
        }
        return returnMessage;
       
    }
    
   
}