force-app/main/default/objects/Atividade__c/Atividade__c.object-meta.xml
<CustomObject>
    <label>Atividade</label>
    <nameField>
        <label>Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atividades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Atividade__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descricao</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Hora__c.field-meta.xml
<CustomField>
    <fullName>Hora__c</fullName>
    <label>Hora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Atividade__c/fields/Projeto__c.field-meta.xml
<CustomField>
    <fullName>Projeto__c</fullName>
    <label>Projeto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Projeto__c/Projeto__c.object-meta.xml
<CustomObject>
    <label>Projeto</label>
    <nameField>
        <label>Projeto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projetos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BuscaDiaADia.cls
@RestResource(urlMapping='/BuscaDiaADia')
global with sharing class BuscaDiaADia {
 
    @HttpGet
    global static void receiveData() {
        
        
        RestRequest req = RestContext.request;  
        Map<String, String> json = req.params;
        System.debug(json);           

        List<String> teste=json.values();
        System.debug(teste);
        

        List<Atividade__c> ativList = [SELECT Name, Data__c, Projeto__c, Hora__c, Descricao__c, Username__c,  HoraExtra__c  
        FROM Atividade__c WHERE Username__c IN: teste];
             
        
        HttpResponse response = new HttpResponse();
        String jsonReturn = SerealizeJsonDiaADia.IntegrationContractJson(ativList);
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(jsonReturn);        
    }
   
}