force-app/main/default/objects/Account/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CellPhone__c.field-meta.xml
<CustomField>
    <fullName>CellPhone__c</fullName>
    <label>CellPhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPFn__c.field-meta.xml
<CustomField>
    <fullName>CPFn__c</fullName>
    <label>CPFn</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactAndLeadSearch.cls
public class ContactAndLeadSearch {
    @AuraEnabled
    public static Object insertTeste(Account acc)
    {
        System.debug(acc);
        insert acc;
        return acc;
    }

    @AuraEnabled
    public static List<Account> dataTable()
    {
        List<Account> data = [SELECT             CPFn__c,
                                                Name,
                                                LastName__c,
                                                BirthDate__c,
                                                Age__c,
                                                CellPhone__c,
                                                Phone
                                        FROM Account];
        return data;
    }
}