force-app/main/default/objects/Account/fields/CellPhone__c.field-meta.xml
<CustomField>
    <fullName>CellPhone__c</fullName>
    <label>CellPhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPFn__c.field-meta.xml
<CustomField>
    <fullName>CPFn__c</fullName>
    <label>CPFn</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DatadeInsercao__c.field-meta.xml
<CustomField>
    <fullName>DatadeInsercao__c</fullName>
    <label>DatadeInsercao</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario__c.field-meta.xml
<CustomField>
    <fullName>Salario__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/WebhookIntegrationAula.cls
@RestResource(urlMapping='/EndpointAula')
global with sharing class WebhookIntegrationAula {

    @HttpPost
    global static String  ReceiveData() {

    RestRequest req = RestContext.request; 
    String json=req.requestBody.toString();
    String jsonReplace = json.replace('dados-pessoais', 'dados_pessoais');
    jsonReplace = jsonReplace.replace('dados-contato', 'dados_contato');
    jsonReplace = jsonReplace.replace('dados-financeiros', 'dados_financeiros');
    DeserealizeWebhookAula query = (DeserealizeWebhookAula)System.JSON.deserialize(jsonReplace, DeserealizeWebhookAula.class);
        System.debug(query);
        String returnMessage = 'Exito';
        if(query.dados.dados_pessoais.nome==null || query.dados.dados_pessoais.nome=='') {
            RestContext.response.statusCode = 400 ; 
            returnMessage = 'Enviar o campo nome corretamente';            
        }
        else {
            String cpf = query.dados.dados_pessoais.cpf;
        List<Account> accList = new List<Account>();
        accList = [SELECT Id, CPFn__c, DatadeInsercao__c, Email__c, CellPhone__c, Salario__c, Name
        FROM Account WHERE CPFn__c = :cpf];
        
        for (Account acc : accList) {
            acc.DatadeInsercao__c = Date.valueOf(query.dados.dados_pessoais.data);
            acc.Email__c = query.dados.dados_contato.email;
            acc.Salario__c =  query.dados.dados_financeiros.salario;
        }
        update accList;
        }
        
        return returnMessage;
    }
}