force-app/main/default/objects/Account/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPFn__c.field-meta.xml
<CustomField>
    <fullName>CPFn__c</fullName>
    <label>CPFn</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Localidade__c.field-meta.xml
<CustomField>
    <fullName>Localidade__c</fullName>
    <label>Localidade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Numero</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountCPFController.cls
public with sharing class AccountCPFController {
    @AuraEnabled
    public static String saveAcc(Account respostas){
    System.debug(respostas);
    insert respostas;    
    return respostas.Id;
    }

    @AuraEnabled
    public static String updateAcc(List<String> listUpdate, String recordId){
    List<Account> acc = [SELECT Localidade__c, Logradouro__c, Estado__c, Cep__c, Numero__c, Bairro__c FROM Account WHERE Id=:recordId];
    List<Account> accounts = new List<Account>();
    for (Account conta : acc) {        
            conta.Logradouro__c=listUpdate[0];
            conta.Numero__c=listUpdate[1];
            conta.Localidade__c=listUpdate[2];
            conta.Estado__c=listUpdate[3];
            conta.Cep__c=listUpdate[4];
            conta.Bairro__c=listUpdate[5];
            accounts.add(conta);
    }
    update accounts;
    
    return 'oi';
    }
    @AuraEnabled
    public static List<Account> selectAcc(){
    Date today = Date.today();
    List<Account> acc = [SELECT Localidade__c, Logradouro__c, Cep__c, Numero__c, BirthDate__c, CPFn__c, LastName__c, Name FROM Account WHERE CreatedDate = TODAY];
    
    return acc;
    }

   
}