force-app/main/default/objects/Account/fields/CPFn__c.field-meta.xml
<CustomField>
    <fullName>CPFn__c</fullName>
    <label>CPFn</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario__c.field-meta.xml
<CustomField>
    <fullName>Salario__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <description>Calculates sales rep commission of 10 percent when opportunity is won.</description>
    <formula>IF( ISPICKVAL( StageName , &quot;Closed Won&quot;) , Amount  * 0.1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Sales rep commission when opportunity is won.</inlineHelpText>
    <label>Commission</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/formAulaTriggerHandler.cls
public with sharing class formAulaTriggerHandler {
    public with sharing class ResponseObject {
        public String name;
        public String cpf;
        public Boolean flag;
    }
    public static void afterInsert(List<Account> accListNew) {
        ResponseObject resp = new ResponseObject();
        for (Account accNew : accListNew) {
            if (accNew.CPFn__c == '09642049910')   {
                resp.name=accNew.Name;
                resp.cpf='09642049920';
                resp.flag=true;
                System.debug('Si ' + accNew.Name);
            }         
            else {
                resp.flag=false;
                System.debug('No ' + accNew.Name);
            }
        }
        if(resp.flag==true) {
            Account acc = new Account(
            CPFn__c=resp.cpf,
            Name='Trigger ' + resp.name
        );
        insert acc;
        }        
    }
    public static void beforeInsert (List<Account> accListNew) {
        Opportunity opp = [SELECT Commission__c FROM Opportunity WHERE 	Name = 'Edge SLA'];
        for (Account accNew : accListNew) {
            System.debug(accNew.Salario__c);
            accNew.Salario__c = opp.Commission__c;            
        }
        
    }

}