force-app/main/default/objects/Account/fields/CPFn__c.field-meta.xml
<CustomField>
    <fullName>CPFn__c</fullName>
    <label>CPFn</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario__c.field-meta.xml
<CustomField>
    <fullName>Salario__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Teste.recordType-meta.xml
<RecordType>
    <fullName>Teste</fullName>
    <active>true</active>
    <label>Teste</label>
</RecordType>

force-app/main/default/classes/aulaBatchTest.cls
@isTest
public with sharing class aulaBatchTest {
    @isTest public static void aulaBatchTest() {
        Date today = Date.today();
        Date myDate =  today.addDays(31);
        Opportunity newOpp = new Opportunity(
            Name = 'Edge SLA',
            StageName = 'Aprovação',             
            CloseDate = myDate
        );
        insert newOpp;
        Account newAccount = new Account(
            Name='Joao',
            CPFn__c ='08553072932',
            Salario__c=9000,
            Email__c='joao@teste.com'
        );
        insert newAccount;
        Account newAccount2 = new Account(
            Name='Joao',
            CPFn__c ='09642049910',
            Salario__c=4100,
            Email__c='jlucasnevessouza@gmail.com'
        );
        insert newAccount2;

        String CRON_EXP = '2 0 0 * * ?';
        String jobId = System.schedule('ScheduledApexTest',
        CRON_EXP,
        new aulaBatch());
 
         Database.executeBatch(new aulaBatch(), 1);
    }
}