force-app/main/default/objects/Account/fields/CPFn__c.field-meta.xml
<CustomField>
    <fullName>CPFn__c</fullName>
    <label>CPFn</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Salario__c.field-meta.xml
<CustomField>
    <fullName>Salario__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/aulaBatch.cls
public with sharing class aulaBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable{
   public void execute(SchedulableContext context) {
       Database.executeBatch(this, 1);
   }
   public Database.queryLocator start(Database.BatchableContext batchanleContext) {
       String xxx = 'SELECT CPFn__c, Salario__c FROM Account WHERE CPFn__c = \'09642049910\'';
       return Database.getQueryLocator(xxx);
   }
   public void execute(Database.BatchableContext batchanleContext, List<Account> acc) {
    AulaChangeCPF.AulaChangeCPF(acc);
   } 
   public void finish(Database.BatchableContext param1){
        System.debug(param1);
   }
}